version: '3.8'

services:
  app:
    build: .
    ports:
      - '4500:4500'
    environment:
      DATABASE_URL: mysql://root:rootpassword@db:3306/salon
      JWT_ACCESS_KEY: secret_assess
      JWT_REFRESH_KEY: secret_refresh
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: salon
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - '8080:80'
